### ISSUE TITLE
Game crashes when right-clicking pipe

### ISSUE THREAD

**Issue by accord1o** [AztechMC/Modern-Industrialization#554] opened 2023-08-23 12:08 UTC
I try delete all mods and click again, but it didn't help. 

![image](https://github.com/AztechMC/Modern-Industrialization/assets/142993878/644f1f93-4536-41ca-afa7-61fc17645a1d)

[crash-2023-08-23_13.57.20-client.txt](https://github.com/AztechMC/Modern-Industrialization/files/12418983/crash-2023-08-23_13.57.20-client.txt)

**Comment by 0x6273** [comment] 2023-08-23 13:25
I think this is dupe of #552

**Comment by Technici4n** [comment] 2023-08-23 14:01
Duplicate of #552

**Closed by Technici4n** 2023-08-23 14:01 UTC
