### ISSUE TITLE
Upgrade Large Tank

### ISSUE THREAD

**Issue by ExodusR** [AztechMC/Modern-Industrialization#176] opened 2021-12-08 10:28 UTC
Hello,

With Friends we are playing on All Of Fabric 4 in 1.17.1, and we construct the Large Tank but we dont understand oh we can upgrade the tank ? 
Thank's for you'r responses !

**Comment by Azercoco** [comment] 2021-12-09 15:39
Just increase the size of the tank (max 7x7x7) without destroying the controller or you will loose its content.

**Comment by ExodusR** [comment] 2021-12-10 17:19
We have construct the 5x5x5 but it doesn't work we don't understand why

**Comment by Azercoco** [comment] 2021-12-12 10:54
Could you provide a screen or something that could help us understand where the problem is ?

**Comment by Azercoco** [comment] 2021-12-27 19:05
Closing it. Reopen if needed

**Closed by Azercoco** 2021-12-27 19:05 UTC
