### ISSUE TITLE
NullPointerException when breaking an item pipe

### ISSUE THREAD

**Issue by yfns** [AztechMC/Modern-Industrialization#799] opened 2024-07-24 10:33 UTC
Specifically it happens when I automatically break an item pipe with a cart from steve's carts 2 and corrupts the save file.

java.lang.NullPointerException: Cannot invoke "aztech.modern_industrialization.pipes.impl.PipeBlockEntity.getNodes()" because "pipeEntity" is null
<details>
<summary>StackTrace</summary>
java.lang.NullPointerException: Cannot invoke "aztech.modern_industrialization.pipes.impl.PipeBlockEntity.getNodes()" because "pipeEntity" is null
	at aztech.modern_industrialization.pipes.impl.PipeBlock.getDrops(PipeBlock.java:247) ~[Modern-Industrialization-2.0.24-all.jar%23604!/:?] {re:classloading}
	at vswe.stevescarts.modules.workers.tools.ModuleDrill.mineBlock(ModuleDrill.java:255) ~[stevescarts-1.20.4-1.2.7-neoforge.jar%23660!/:?] {re:classloading}
	at vswe.stevescarts.modules.workers.tools.ModuleDrill.mineBlockAndRevive(ModuleDrill.java:187) ~[stevescarts-1.20.4-1.2.7-neoforge.jar%23660!/:?] {re:classloading}
	at vswe.stevescarts.modules.workers.tools.ModuleDrill.work(ModuleDrill.java:125) ~[stevescarts-1.20.4-1.2.7-neoforge.jar%23660!/:?] {re:classloading}
	at vswe.stevescarts.entities.EntityMinecartModular.work(EntityMinecartModular.java:1403) ~[stevescarts-1.20.4-1.2.7-neoforge.jar%23660!/:?] {re:classloading}
	at vswe.stevescarts.entities.EntityMinecartModular.onCartUpdate(EntityMinecartModular.java:1215) ~[stevescarts-1.20.4-1.2.7-neoforge.jar%23660!/:?] {re:classloading}
	at vswe.stevescarts.entities.EntityMinecartModular.tick(EntityMinecartModular.java:1194) ~[stevescarts-1.20.4-1.2.7-neoforge.jar%23660!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:755) ~[client-1.20.4-20231207.154220-srg.jar%23699!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.random.ServerLevelMixin from mod servercore,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:servercore.common.mixins.json:features.activation_range.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:features.spawn_chunks.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:optimizations.sync_loads.ServerLevelMixin from mod servercore,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin from mod immersiveengineering,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin from mod hyperbox,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:A}
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:556) ~[client-1.20.4-20231207.154220-srg.jar%23699!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mffs.mixins.json:LevelMixin from mod mffs,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin from mod kubejs,pl:mixin:APP:lucent.mixins.json:LevelMixin from mod lucent,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:401) ~[client-1.20.4-20231207.154220-srg.jar%23699!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.random.ServerLevelMixin from mod servercore,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:servercore.common.mixins.json:features.activation_range.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:features.spawn_chunks.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:optimizations.sync_loads.ServerLevelMixin from mod servercore,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin from mod immersiveengineering,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin from mod hyperbox,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[client-1.20.4-20231207.154220-srg.jar%23699!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:381) ~[client-1.20.4-20231207.154220-srg.jar%23699!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:servercore.common.mixins.json:optimizations.ticking.chunk.random.ServerLevelMixin from mod servercore,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin from mod modernfix,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin from mod modernfix,pl:mixin:APP:servercore.common.mixins.json:features.activation_range.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:features.spawn_chunks.ServerLevelMixin from mod servercore,pl:mixin:APP:servercore.common.mixins.json:optimizations.sync_loads.ServerLevelMixin from mod servercore,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin from mod immersiveengineering,pl:mixin:APP:hyperbox.mixins.json:ServerLevelMixin from mod hyperbox,pl:mixin:APP:kubejs-common.mixins.json:ServerLevelMixin from mod kubejs,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin from mod betterdeserttemples,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:969) ~[client-1.20.4-20231207.154220-srg.jar%23699!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:855) ~[client-1.20.4-20231207.154220-srg.jar%23699!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:106) ~[client-1.20.4-20231207.154220-srg.jar%23699!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin from mod modernfix,pl:mixin:APP:lithostitched.mixins.json:client.IntegratedServerMixin from mod lithostitched,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:700) ~[client-1.20.4-20231207.154220-srg.jar%23699!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:255) ~[client-1.20.4-20231207.154220-srg.jar%23699!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}
</details>

**Comment by Technici4n** [comment] 2024-07-24 10:52
Duplicate of https://github.com/AztechMC/Modern-Industrialization/issues/745

**Closed as not planned by Technici4n** 2024-07-24 10:52 UTC
