### ISSUE TITLE
Can bypass replicator tag check by Nbt-attached blocks (block entity)

### ISSUE THREAD

**Issue by aria1th** [AztechMC/Modern-Industrialization#270] opened 2022-03-17 16:23 UTC
Chests with NBT data, or other machine / items that contains item data can bypass replicator blacklist.

**Comment by Technici4n** [comment] 2022-03-17 20:58
I don't really see what can be done in that case tbh, but it is semi-intended that the replicator can most likely duplicate items contained by other items.

**Comment by yorii** [comment] 2022-03-18 03:38
Pack creators can add whichever item tags they want to the replicator blacklist using KubeJS.

**Comment by Technici4n** [comment] 2022-03-21 09:21
Going to close this as "works as intended" :P

**Closed by Technici4n** 2022-03-21 09:21 UTC
