### ISSUE TITLE
crash with Interdimensional SU 

### ISSUE THREAD

**Issue by Azruine** [AztechMC/Modern-Industrialization#258] opened 2022-02-18 19:45 UTC
placing IDSU adjecent to output side of storage block makes game crash.

crash log: https://pastebin.com/3P8ByyGL

possible solution: 
in AbstractBlockMachineEntity.java

    @Override
    public void tick() 
    {
        if (!level.isClientSide) 
        {
            EnergyMoveable insertable = MOVEABLE.find(this.getLevel(), this.getBlockPos().relative(orientation.outputDirection),
                    orientation.outputDirection.getOpposite());
            if (insertable instanceof EnergyInsertable && ((EnergyInsertable) insertable).canInsert(to)) 
            {
                energy.insertEnergy((EnergyInsertable) insertable);
            }
        }
        this.setChanged();
    }

Sorry for not PRing, but im so tired now :/

**Comment by Technici4n** [comment] 2022-02-21 21:17
Duplicate of #247

**Comment by Technici4n** [comment] 2022-02-21 21:18
Oh wait nevermind :P

**Closed** 2022-04-25 13:13 UTC
