### ISSUE TITLE
Modpack Crash Report

### ISSUE THREAD

**Issue by MacatMovie** [AztechMC/Modern-Industrialization#402] opened 2022-11-23 23:55 UTC
Hello.
I've been playing a big-scale custom-made modpack with a few friends and recently updated all the contents + added a few new mods and I've been having an issue with the centrifuge blocks. Any time it is powered it crashes the game on singleplayer or server on multiplayer and cannot re-enter that world/server until I remove it. I do that by porting the world into the older version of modpack, unplugging the block and then porting the world back. 

Since the centrifuge block is quite crucial for the progression of the mod and I'm not sure what's causing it, I would appreciate any help. I've tried multiple versions of Modern Industrialization mod, so I suppose another mod could be causing it?

I'm linking the crash report here:
[crash-2022-11-24_00.29.54-server.txt](https://github.com/AztechMC/Modern-Industrialization/files/10079811/crash-2022-11-24_00.29.54-server.txt)

**Comment by MacatMovie** [comment] 2022-11-24 00:09
And here's a log file of me creating a new world and recreating the crash:
[2022-11-24-1.log](https://github.com/AztechMC/Modern-Industrialization/files/10079868/2022-11-24-1.log)

**Comment by HunturioDevelopment** [comment] 2022-11-29 19:40
Hey Devs,
I found out, that the problem of the Centrifuge (when it is powered) crashing the server/singeplayer world could be caused by the plant oil recipes the centrifuge is loading and all the plant items/blocks the mod Immersive Weathering is adding to the game. Maybe it is something like the solution for [https://github.com/AztechMC/Modern-Industrialization/issues/370#issue-1328625614](url). So if you can look into it, it would be really appreciated. If you need another crash log, i can send you one or post it.

**Comment by MacatMovie** [comment] 2022-11-30 18:40
Heya.
Thanks HunturioDevelopment, for solving this problem. I've tested it and it now works normally. 
It is sad though, that the only way of fixing this is by removing Immersive Weathering mod, because it now leaves lot's of random blocks missing all over the world.
Thanks again and I hope the Devs can eventually fix it.

**Comment by Technici4n** [comment] 2022-11-30 23:24
Did you try updating MI to 1.4.2?

**Comment by Technici4n** [comment] 2022-11-30 23:28
Ah nevermind, I see what is wrong. This is really an issue with immersive weathering registering null compostable items afaict. We'll work around it in the next MI release, but that will take some time, and I would like them to also fix it on their side, if I correctly understood the issue.

**Comment by HunturioDevelopment** [comment] 2022-12-01 08:28
Hey,
thank you for looking into it. I have opened up an issue over there at Immersive Weathering and in hopes that they can fix the problem with null compostable items on their side.

**Comment by Technici4n** [comment] 2023-01-01 20:37
Fixed in 6560f8c8. (MI v1.5.0-beta)

**Closed by Technici4n** 2023-01-01 20:37 UTC
Labels: bug
