### ISSUE TITLE
Game won't start after updating to 2.2.26

### ISSUE THREAD

**Issue by MuteTiefling** [AztechMC/Modern-Industrialization#947] opened 2024-12-04 13:55 UTC
Logs: https://mclo.gs/P7jGOYA

I've updated all mods in e10-dev and started encountering this issue. After some trial and error I've narrowed it down to Modern Industrialization. As soon as I update it, I'm no longer able to launch.

The errors seem a bit misleading. At first because it's referencing cumulus I thought the issue was Aether, so I disabled that an just got a different error, leading me down a rabbit hole that ultimately ended with MI.

**Comment by Swedz** [comment] 2024-12-04 13:59
Weird that the error shows up like that, but it is likely because the latest version of MI contains changes I have submitted but EI has not been updated to follow these changes. I am waiting on some other changes to get merged before updating. Not an issue on MI's end. I recommend downgrading temporarily until there's a better stopping point for EI to update to.

**Comment by MuteTiefling** [comment] 2024-12-04 14:03
Alright, sounds good. I was told you'd likely also need the latest log so I'm adding it here in case: https://mclo.gs/ReEqFMK

Sounds like you have it under control already though. Thanks!

**Comment by MuteTiefling** [comment] 2024-12-04 15:37
Take two on the logs: 
https://mclo.gs/HeRcYaU
https://mclo.gs/O1uAD4G

**Comment by Swedz** [comment] 2024-12-04 18:05
Could you test to make sure it's being caused by EI and Tesseract API? The errors are a bit unusual.

**Comment by MuteTiefling** [comment] 2024-12-04 19:11
Sure just launch with updated MI but with EI disabled?

**Comment by Swedz** [comment] 2024-12-04 19:13
Yeah, and Tesseract API. Also MI Tweaks if you have that.

**Comment by MuteTiefling** [comment] 2024-12-04 21:05
loads fine like that. here's the log in case you need it: https://mclo.gs/RZWdE0y

**Comment by Swedz** [comment] 2024-12-12 09:56
Just released the update for EI, MI Tweaks, and Tesseract API. Update those and if the issue persists you can reopen the issue.

**Closed as completed by Swedz** 2024-12-12 09:56 UTC
