### ISSUE TITLE
Server Crash Involving pipes

### ISSUE THREAD

**Issue by funyman333222** [AztechMC/Modern-Industrialization#175] opened 2021-12-07 21:51 UTC
Every time i disconnect from my server that i have this, and other mods on, and let it run for a while, it will eventually cause a crash and i would have to restart the server

this right here is the main java error im receiving
i got 2 crashes with the same report about 4-5 hours between each other
```
java.lang.UnsupportedOperationException: Internal MI pipe bug: spanned chunk was not loaded anymore.
	at aztech.modern_industrialization.pipes.api.PipeNetworkManager.tickNetworks(PipeNetworkManager.java:75)
	at aztech.modern_industrialization.pipes.impl.PipeNetworks.lambda$static$2(PipeNetworks.java:104)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:108)
	at net.minecraft.class_1937.handler$zlj000$tickWorldAfterBlockEntities(class_1937.java:3094)
	at net.minecraft.class_1937.method_18471(class_1937.java:479)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Technici4n** [comment] 2021-12-07 22:02
I have already seen this crash, but I have no clue what its cause is. It looks like some chunks are not unloading properly. If anyone can provide a way to reproduce this, I'm happy to hear it.

**Comment by funyman333222** [comment] 2021-12-08 02:11
i hope yall figure it out soon because most of my friend i play with are from diffrent countrys and i dont want the server to go out on them again

**Comment by Technici4n** [comment] 2021-12-08 19:10
The fix will be in the next alpha.

**Closed** 2021-12-08 19:10 UTC

**Comment by funyman333222** [comment] 2021-12-09 15:19
thank you!
