### ISSUE TITLE
Modern-Industrialization-0.3.7 is somehow incompatible with version 1.16.4 of minecraft (with Fabric)

### ISSUE THREAD

**Issue by heyjudek** [AztechMC/Modern-Industrialization#30] opened 2020-11-12 07:23 UTC
Whenever I try to launch the game, I just get an error saying "modid requires Minecraft 1.15.x". I have triple checked and on the cursefurge it says that this version of Modern Industrialization is meant for the version 1.16.4.
What am I doing wrong?

**Comment by Technici4n** [comment] 2020-11-12 07:35
It might be another mod... Can you send me your logs please ?

**Comment by heyjudek** [comment] 2020-11-12 08:19
Sure, by the way I have went as low as 0.3.2 version. Same thing all the time:
Fabric loader says: "Could not find required mod: modid requires {minecraft @ [1.15.x]}"

And here's the info from the developer console:
[09:18:46] [main/INFO]: Loading for game Minecraft 1.16.4
[09:18:46] [ForkJoinPool-1-worker-7/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[09:18:46] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 9
[09:18:46] [ForkJoinPool-1-worker-7/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[09:18:46] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:18:46] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components-block" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:18:46] [ForkJoinPool-1-worker-6/WARN]: The mod "cardinal-components-world" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:18:46] [ForkJoinPool-1-worker-7/WARN]: The mod "cardinal-components-scoreboard" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:18:46] [ForkJoinPool-1-worker-7/WARN]: The mod "cardinal-components-level" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:18:46] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components-chunk" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:18:46] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:18:46] [ForkJoinPool-1-worker-6/WARN]: The mod "cardinal-components-util" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:18:46] [ForkJoinPool-1-worker-7/WARN]: The mod "cardinal-components-item" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[09:18:46] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[09:18:46] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: modid requires {minecraft @ [1.15.x]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:173) ~[fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:739) ~[fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:210) ~[fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:200) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:128) [fabric-loader-0.10.6+build.214.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.10.6+build.214.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170) ~[fabric-loader-0.10.6+build.214.jar:?]
	... 5 more

**Comment by Technici4n** [comment] 2020-11-12 08:21
Do you have a custom mod or something? This issue is from a mod named `modid`, probably someone forgot to put the id of their mod...

**Comment by heyjudek** [comment] 2020-11-12 08:30
All my mods were from curseforge. How can I find which one it is?
I appreciate your support.

**Comment by heyjudek** [comment] 2020-11-12 08:30
I have foolishly thought that modid refers to "Modern Industrialization" :)

**Comment by Technici4n** [comment] 2020-11-12 08:56
Ohhhhh that's why... :) I suggest you start anew and add the mods one by one until you find the cause of this issue.

**Comment by heyjudek** [comment] 2020-11-12 09:36
Got it, thanks again :)

**Comment by Technici4n** [comment] 2020-11-12 09:37
You found the culprit?

**Comment by Technici4n** [comment] 2020-11-16 22:47
Closing this

**Closed by Technici4n** 2020-11-16 22:47 UTC
